=== pirati-cz/pravo/docs/schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

     <xs:simpleType name="Text">
          <xs:restriction base="xs:string">
               <xs:pattern value="[\S\s]*"/>
          </xs:restriction>
     </xs:simpleType>

     <xs:complexType name="a">
          <xs:simpleContent>
               <xs:extension base="Text">
                    <xs:attribute name="sbirka" type="xs:gYear" use="required"/>
                    <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
               </xs:extension>
          </xs:simpleContent>
     </xs:complexType>

     <xs:complexType name="paragraf">
          <xs:simpleContent>
               <xs:extension base="Text">
                    <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
               </xs:extension>
          </xs:simpleContent>
     </xs:complexType>

     <xs:complexType name="odstavec" mixed="true">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
               <xs:element name="a" type="a"/>
          </xs:choice>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
     </xs:complexType>

     <xs:complexType name="clanek" mixed="true">
          <xs:sequence>
               <xs:element name="odstavec" type="odstavec" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
     </xs:complexType>

     <!-- Novel -->
     <xs:complexType name="novela">
          <xs:choice>
               <xs:element name="paragraf" type="paragraf" minOccurs="0" maxOccurs="unbounded"/>
          </xs:choice>
          <xs:attribute name="sbirka" type="xs:gYear" use="required"/>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
     </xs:complexType>

     <!-- Root types -->
     <xs:complexType name="ustavni_dekret">
          <xs:sequence>
               <xs:element name="paragraf" type="paragraf" minOccurs="1" maxOccurs="unbounded"/>
          </xs:sequence>
          <xs:attribute name="nazev" type="xs:string" use="required"/>
          <xs:attribute name="sbirka" type="xs:gYear" use="required"/>
          <xs:attribute name="castka" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="datum_schvaleni" type="xs:date" use="required"/>
          <xs:attribute name="datum_platnosti" type="xs:date" use="required"/>
          <xs:attribute name="datum_ucinnosti" type="xs:date" use="required"/>
     </xs:complexType>

     <xs:complexType name="ustavni_zakon">
          <xs:choice minOccurs="0" maxOccurs="unbounded">
               <xs:element name="clanek" type="clanek"/>
               <xs:element name="novela" type="novela"/>
          </xs:choice>
          <xs:attribute name="nazev" type="xs:string" use="required"/>
          <xs:attribute name="sbirka" type="xs:gYear" use="required"/>
          <xs:attribute name="castka" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="datum_schvaleni" type="xs:date" use="required"/>
          <xs:attribute name="datum_platnosti" type="xs:date" use="required"/>
          <xs:attribute name="datum_ucinnosti" type="xs:date" use="required"/>
     </xs:complexType>

     <xs:complexType name="zakon">
     </xs:complexType>

     <xs:complexType name="vyhlaska" mixed="true">
          <xs:attribute name="nazev" type="xs:string" use="required"/>
          <xs:attribute name="sbirka" type="xs:gYear" use="required"/>
          <xs:attribute name="castka" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="datum_schvaleni" type="xs:date" use="required"/>
          <xs:attribute name="datum_platnosti" type="xs:date" use="required"/>
          <xs:attribute name="datum_ucinnosti" type="xs:date" use="required"/>
     </xs:complexType>

     <xs:complexType name="prezidentsky_dekret">
          <xs:attribute name="nazev" type="xs:string" use="required"/>
          <xs:attribute name="sbirka" type="xs:gYear" use="required"/>
          <xs:attribute name="castka" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="cislo" type="xs:positiveInteger" use="required"/>
          <xs:attribute name="datum_schvaleni" type="xs:date" use="required"/>
          <xs:attribute name="datum_platnosti" type="xs:date" use="required"/>
          <xs:attribute name="datum_ucinnosti" type="xs:date" use="required"/>
     </xs:complexType>

     <!-- Root -->
     <xs:element name="ustavni_dekret" type="ustavni_dekret"/>
     <xs:element name="ustavni_zakon" type="ustavni_zakon"/>
     <xs:element name="zakon" type="zakon"/>
     <xs:element name="vyhlaska" type="vyhlaska"/>
     <xs:element name="prezidentsky_dekret" type="prezidentsky_dekret"/>

</xs:schema>

=== pirati-cz/pravo/cze/1945_3.xml
<?xml version="1.0"?>
<prezidentsky_dekret
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="https://github.com/pirati-cz/docs/schema.xsd"
     nazev="Dekret presidenta republiky, kterým se mění a doplňují některá ustanovení vojenského trestního zákona a branného zákona"
     sbirka="1945"
     castka="2"
     cislo="3"
     datum_schvaleni="1945-04-23"
     datum_platnosti="1945-04-30"
     datum_ucinnosti="1945-04-30">
     <paragraf cislo="1">
          Ustanovení § 194 vojenského trestního zákona doplňuje se dalším odstavcem tohoto znění:
          <odstavec cislo="2">
               "(2) Kromě toho v době války propadne zběh trestu smrti zastřelením, uznal-li hlavní velitel pro vzmáhající se zběhnutí za nutné pohroziti tímto trestem i bez vyhlášení stanného práva a uprchl-li zběh přes tuto jemu známou pohrůžku od jakéhokoliv vojenského útvaru v úmyslu, aby se tím vyhnul službě v poli. To platí i tehdy, kdyby jinak zběh nemohl býti odsouzen k trestu smrti, poněvadž se sám dobrovolně dostavil anebo přihlásil (§ 195 a)."
          </odstavec>
          Ustanovení § 294 vojenského trestního zákona se doplňuje dalším odstavcem tohoto znění:
          <odstavec cislo="2">
               "(2) V době války trestá se však zločin tento trestem smrti zastřelením, uznal-li hlavní velitel pro vzmáhající se sebepoškození za nutné i bez vyhlášení stanného práva pohroziti tímto trestem a dopustil-li se pachatel tohoto zločinu přes tuto jemu známou pohrůžku."
          </odstavec>
          Ustanovení § 295 vojenského trestního zákona se doplňuje dalším odstavcem tohoto znění:
          <odstavec cislo="2">
               "(2) V době války trestá se zločin tento žalářem od pěti do deseti let, trestem smrti zastřelením však, uznal-li hlavní velitel pro vzmáhající se sebepoškození za nutné i bez vyhlášení stanného práva pohroziti tímto trestem a dopustil-li se pachatel tohoto zločinu přes tuto jemu známou pohrůžku."
          </odstavec>
     </paragraf>
     <paragraf cislo="2">Trest na svobodě, stanovený § 50 branného zákona Československé republiky ze dne 19. března 1920, č. 193 Sb. z. a n., za neuposlechnutí povolávacího rozkazu k činné službě za mobilisace, zvyšuje se na tuhé vězení do pěti let.</paragraf>
     <paragraf cislo="3">Účinnost tohoto dekretu nastává dnem jeho vyhlášení.</paragraf>
     <paragraf cislo="4">Provedením tohoto dekretu pověřuje se ministr národní obrany.</paragraf>
</prezidentsky_dekret>

=== pirati-cz/pravo/cze/1946_153.xml
<?xml version="1.0"?>
<ustavni_zakon
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="https://github.com/pirati-cz/docs/schema.xsd"
     nazev="Ústavní zákon, jímž se mění ústavní dekret presidenta republiky ze dne 2. dubna 1945, č. 1 Sb., o nové organisaci vlády a ministerstev v době přechodné"
     sbirka="1946"
     castka="64"
     cislo="153"
     datum_schvaleni="1946-07-10"
     datum_platnosti="1946-07-17"
     datum_ucinnosti="1946-07-17">
     <clanek cislo="1">
          <odstavec cislo="1">
               V § 2 ústavního dekretu č. <a cislo="1" sbirka="1945">1/1945</a> Sb. ve výpočtu ministerstev se provádějí tyto změny:
               1. za ministerstvo dopravy zařazuje se ministerstvo techniky,
               2. ministerstvo ochrany práce a sociální péče označuje se jako ministerstvo sociální péče,
               3. na konci výpočtu připojuje se ministerstvo pro sjednocení zákonů.
          </odstavec>
          <odstavec cislo="2">
               V § 3 téhož ústavního dekretu připojuje se na konci tato věta: "Místo státního tajemníka může zůstati neobsazeno".
          </odstavec>
     </clanek>
     <clanek cislo="2">
          Tento ústavní zákon nabývá účinnosti dnem vyhlášení; provedou jej všichni členové vlády.
     </clanek>
     <novela sbirka="1945" cislo="1">
          <paragraf cislo="2">
               V čele státní správy jsou tato ministerstva:
               ministerstvo zahraničních věcí,
               ministerstvo národní obrany,
               ministerstvo zahraničního obchodu,
               ministerstvo vnitra,
               ministerstvo financí,
               ministerstvo školství a osvěty,
               ministerstvo spravedlnosti,
               ministerstvo informací,
               ministerstvo průmyslu,
               ministerstvo zemědělství,
               ministerstvo vnitřního obchodu,
               ministerstvo dopravy,
               ministerstvo techniky,
               ministerstvo pošt,
               ministerstvo sociální péče,
               ministerstvo zdravotnictví,
               ministerstvo výživy,
               ministerstvo pro sjednocení zákonů.
          </paragraf>
          <paragraf cislo="3">V ministerstvech zahraničních věcí, národní obrany a zahraničního obchodu jsou státní tajemníci, kteří jsou členy vlády. Je-li ministr Čech, bude státní tajemník Slovák a naopak. Místo státního tajemníka může zůstati neobsazeno.</paragraf>
     </novela>
</ustavni_zakon>
